### PR TITLE
Merge back changes

### PR DESCRIPTION
**Pull request by BlueWinds**
It'd be helpful if you merged my latest commits back into your repository - there are still some conflicts, and it would make me examining things a lot easier.

### CODE REVIEW

**Comment by ParaplegicRacehorse** [comment]
Yeah, I'm still trying to figure out how to do that. The git help is not very useful on that topic

**Comment by ParaplegicRacehorse** [comment]
Okay, I think I got that figured out. Not sure if I made the same choices when merging conflicts as you did. The cues in the files aren't very useful to me until I get more accustomed to doing this.

**Comment by BlueWinds** [comment]
I find the cues incredibly confusing too - I can never tell which branch a given line came from. >.> Mostly what I end up doing is moving the conflicting lines next to each other and deciding which one to keep.

**Comment by BlueWinds** [comment]
But yep, looks like you got everything right. There's an extra blank line in your branch, but it's harmless.

https://github.com/BlueWinds/LapisAzurai/compare/master...ParaplegicRacehorse:master

**Comment by ParaplegicRacehorse** [comment]
Now to figure out how to merge master into my working branch, instead of the other way around. Git is supposed to be one of the easier to learn VCSes. If so, I'd hate to see how the others work.

**Comment by BlueWinds** [comment]
Ah, that's one of the easier things.

```
git checkout working-branch-whatever-its-called
git merge master
```

Basically, think of "git merge ABC" as "merge from ABC into wherever I am now".

**Pull request merged**
